services:
  db:
    container_name: postgres
    image: postgres:15.2
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  frasini-api:
    container_name: frasini-api
    image: cimu/frasini-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  frasini-react:
    container_name: frasini-react
    image: cimu/frasini-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8080
    ports:
      - "3000:5173"
    depends_on:
      - frasini-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: